version: '3.8'

services:
  predictionbot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=predictionbot
      - ADMIN_EMAIL=ishimweeli0@gmail.com
      - ADMIN_PASSWORD=Password@123
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=ishimweeli0@gmail.com
      - SPRING_MAIL_PASSWORD=mbfp juhd meml qudv
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - APP_REGISTRATION_URL=http://localhost:3000/register
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql3.freesqldatabase.com:3306/sql3716607?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=sql3716607
      - SPRING_DATASOURCE_PASSWORD=88ETqn3Lr6
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=2000000000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASIC_BINDER=TRACE
      - JWT_SECRET=yourheyisnamedhereOnthiscahrfdsnmmvfhgjgjjgjhjhyiyyjyjjkjkukujyujukjukukujujujujujkukukukukujukukukyhyj5thjtrkrjrkrjrjyjhtknb
      - JWT_EXPIRATION=3600000
      - OPENAPI_DEV_URL=http://localhost:8080
      - OPENAPI_PROD_URL=https://yourdomain.com
      - CORS_ALLOWED_ORIGIN=http://localhost:3000
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_CREDENTIALS=true
      - CORS_CORS_CONFIGURATION=/**